"""Constants for chat API, agent behavior, and background tasks."""

CHAT_API_PREFIX = "/api/chat"
CHAT_API_TAG = "chat"

CHAT_RATE_LIMIT = "10/minute"
CHAT_MESSAGE_EVENT = "chat_message"
CHAT_MESSAGE_STATUS_IN_PROGRESS = "in_progress"
CHAT_TURN_STARTED_EVENT = "chat_turn_started"
CHAT_TURN_COMPLETED_EVENT = "chat_turn_completed"

MAX_TOOL_ITERATIONS = 6
MAX_HISTORY_MESSAGES = 20
CHAT_JOB_CONTENT_PREVIEW_MAX_CHARS = 200
CHAT_RESEARCH_DIRECTION_LOG_MAX_CHARS = 80

PROCESS_CHAT_TURN_TASK_NAME = "app.chat.tasks.process_chat_turn"
PROCESS_CHAT_TURN_MAX_RETRIES = 2
PROCESS_CHAT_TURN_DEFAULT_RETRY_DELAY_SECONDS = 30
PROCESS_CHAT_TURN_SOFT_TIME_LIMIT_SECONDS = 600
PROCESS_CHAT_TURN_TIME_LIMIT_SECONDS = 660
