"""Constants for chair API, repository, and background tasks."""

CHAIRS_API_PREFIX = "/api/chairs"
CHAIRS_API_TAG = "chairs"

CHAIR_LIST_DEFAULT_LIMIT = 100
CHAIR_LIST_DEFAULT_OFFSET = 0
CHAIR_SEARCH_DEFAULT_K = 5
CHAIR_SNIPPET_MAX_CHARS = 300

EMBED_CHAIR_TASK_NAME = "app.chairs.tasks.embed_chair_description"
EMBED_CHAIR_MAX_RETRIES = 3
EMBED_CHAIR_DEFAULT_RETRY_DELAY_SECONDS = 60
EMBED_CHAIR_SOFT_TIME_LIMIT_SECONDS = 120
EMBED_CHAIR_TIME_LIMIT_SECONDS = 180
