"""Constants for paper API and repository behavior."""

PAPERS_API_PREFIX = "/api/papers"
PAPERS_API_TAG = "papers"

PAPER_LIST_DEFAULT_LIMIT = 50
PAPER_LIST_MIN_LIMIT = 1
PAPER_LIST_MAX_LIMIT = 200
PAPER_LIST_DEFAULT_OFFSET = 0
PAPER_LIST_MIN_OFFSET = 0
