"""Numeric API constants for admin endpoints."""

ADMIN_USER_LIST_DEFAULT_LIMIT = 50
ADMIN_USER_LIST_MIN_LIMIT = 1
ADMIN_USER_LIST_MAX_LIMIT = 200
ADMIN_USER_LIST_DEFAULT_OFFSET = 0
ADMIN_USER_LIST_MIN_OFFSET = 0
