"""Numeric API constants for scraper endpoints."""

SCRAPE_SINCE_DAYS_DEFAULT = 3650
SCRAPE_SINCE_DAYS_MIN = 30
SCRAPE_SINCE_DAYS_MAX = 3650
SCRAPE_MAX_RESULTS_DEFAULT = 250
SCRAPE_MAX_RESULTS_MIN = 1
SCRAPE_MAX_RESULTS_MAX = 500
