"""Constants for thesis API and repository behavior."""

THESES_API_PREFIX = "/api/theses"
THESES_API_TAG = "theses"

THESIS_LIST_DEFAULT_LIMIT = 20
THESIS_LIST_MIN_LIMIT = 1
THESIS_LIST_MAX_LIMIT = 100
THESIS_LIST_DEFAULT_OFFSET = 0
THESIS_LIST_MIN_OFFSET = 0

EMBED_THESIS_TASK_NAME = "app.theses.tasks.embed_thesis"
EMBED_THESIS_MAX_RETRIES = 3
EMBED_THESIS_DEFAULT_RETRY_DELAY_SECONDS = 60
EMBED_THESIS_SOFT_TIME_LIMIT_SECONDS = 120
EMBED_THESIS_TIME_LIMIT_SECONDS = 180
