"""LLM enrichment provider constants."""

TAG_FUZZY_THRESHOLD = 0.82
SUMMARY_TEMPERATURE = 0.3
SUMMARY_MAX_TOKENS = 250
TAG_TEMPERATURE = 0.1
TAG_MAX_TOKENS = 150
MAX_GENERATED_TAGS = 5
MAX_SUMMARY_CHARS = 1800
