"""OpenAlex provider constants."""

OPENALEX_API_BASE_URL = "https://api.openalex.org"
OPENALEX_DEFAULT_TIMEOUT_SECONDS = 20.0
OPENALEX_MAX_PAGE_SIZE = 100
OPENALEX_AUTHOR_LOOKUP_PAGE_SIZE = 5
OPENALEX_DAYS_PER_YEAR = 365
