"""Constants for scraper HTTP API behavior."""

SCRAPER_API_PREFIX = "/api/scraper"
SCRAPER_API_TAG = "scraper"

SCRAPE_SINCE_DAYS_DEFAULT = 3650
SCRAPE_SINCE_DAYS_MIN = 30
SCRAPE_SINCE_DAYS_MAX = 3650
SCRAPE_MAX_RESULTS_DEFAULT = 250
SCRAPE_MAX_RESULTS_MIN = 1
SCRAPE_MAX_RESULTS_MAX = 500
