"""Constants for scraper background task behavior."""

SCRAPE_CHAIR_TASK_NAME = "app.scraper.tasks.scrape_chair_papers"
SCRAPE_CHAIR_MAX_RETRIES = 2
SCRAPE_CHAIR_DEFAULT_RETRY_DELAY_SECONDS = 60
SCRAPE_CHAIR_SOFT_TIME_LIMIT_SECONDS = 120
SCRAPE_CHAIR_TIME_LIMIT_SECONDS = 180
SCRAPE_CHAIR_COMPLETE_EVENT = "scrape_chair_complete"

SCRAPE_RESEARCHER_TASK_NAME = "app.scraper.tasks.scrape_researcher_papers"
SCRAPE_RESEARCHER_MAX_RETRIES = 3
SCRAPE_RESEARCHER_DEFAULT_RETRY_DELAY_SECONDS = 30
SCRAPE_RESEARCHER_SOFT_TIME_LIMIT_SECONDS = 600
SCRAPE_RESEARCHER_TIME_LIMIT_SECONDS = 660
SCRAPE_RESEARCHER_COMPLETE_EVENT = "scrape_researcher_complete"

SCRAPE_ALL_CHAIRS_TASK_NAME = "app.scraper.tasks.scrape_all_chairs"
SCRAPE_ALL_CHAIRS_MAX_RETRIES = 0
SCRAPE_ALL_CHAIRS_SOFT_TIME_LIMIT_SECONDS = 120
SCRAPE_ALL_CHAIRS_TIME_LIMIT_SECONDS = 180
SCRAPE_ALL_CHAIRS_ADMIN_LOOKUP_LIMIT = 1
SCRAPE_ALL_CHAIRS_FALLBACK_USER_ID = 1
SCRAPE_ALL_CHAIRS_TRIGGER = "beat"

DISCOVER_CHAIR_EMPLOYEES_TASK_NAME = "app.scraper.tasks.discover_chair_employees"
DISCOVER_CHAIR_EMPLOYEES_MAX_RETRIES = 2
DISCOVER_CHAIR_EMPLOYEES_DEFAULT_RETRY_DELAY_SECONDS = 60
DISCOVER_CHAIR_EMPLOYEES_SOFT_TIME_LIMIT_SECONDS = 120
DISCOVER_CHAIR_EMPLOYEES_TIME_LIMIT_SECONDS = 180
DISCOVER_CHAIR_EMPLOYEES_COMPLETE_EVENT = "discover_chair_employees_complete"

ENRICH_PAPER_TASK_NAME = "app.scraper.tasks.enrich_paper"
ENRICH_PAPER_MAX_RETRIES = 3
ENRICH_PAPER_DEFAULT_RETRY_DELAY_SECONDS = 30
ENRICH_PAPER_SOFT_TIME_LIMIT_SECONDS = 120
ENRICH_PAPER_TIME_LIMIT_SECONDS = 180
ENRICH_PAPER_COMPLETE_EVENT = "enrich_paper_complete"
