"""Constants for student background tasks."""

PARSE_TRANSCRIPT_TASK_NAME = "app.students.tasks.parse_transcript"
STUDENTS_API_PREFIX = "/api/students"
STUDENTS_API_TAG = "students"
STUDENT_TRANSCRIPT_MAX_PDF_SIZE_BYTES = 10 * 1024 * 1024
STUDENT_TRANSCRIPT_MAX_PDF_SIZE_LABEL = "10 MB"
STUDENT_TRANSCRIPT_ACCEPTED_CONTENT_TYPES = ("application/pdf", "application/octet-stream")
STUDENT_PROGRAM_MAX_LENGTH = 255
STUDENT_SEMESTER_MIN = 1
STUDENT_SEMESTER_MAX = 30
TRANSCRIPT_SOFT_TIME_LIMIT_ENV = "TRANSCRIPT_SOFT_TIME_LIMIT"
TRANSCRIPT_HARD_TIME_LIMIT_ENV = "TRANSCRIPT_HARD_TIME_LIMIT"
TRANSCRIPT_SOFT_TIME_LIMIT_DEFAULT_SECONDS = 1800
TRANSCRIPT_HARD_TIME_LIMIT_DEFAULT_SECONDS = 1860
PARSE_TRANSCRIPT_MAX_RETRIES = 3
PARSE_TRANSCRIPT_DEFAULT_RETRY_DELAY_SECONDS = 120
